// <auto-generated />
using System;
using AutoTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AutoTracker.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AutoTracker.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("AutoTracker.Models.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthorizationConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClientNotified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DamagePhotosTaken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinalPhotosTaken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PartsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QualityChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepairCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VehicleReceived")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId")
                        .IsUnique();

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("AutoTracker.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("AutoTracker.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AutoTracker.Models.ClientTrackingAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ClientTrackingAccesses");
                });

            modelBuilder.Entity("AutoTracker.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AutoTracker.Models.CompanySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankingDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CKNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecklistFooterText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanySignatureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanySignaturePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultConsumables")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultFreight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultSundries")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultWasteDisposal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabourRatePerHour")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastInvoiceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastQuoteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MechanicalRatePerHour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaintRatePerPanel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PanelBeatingRatePerHour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteFooterText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotePrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StripAssembleRatePerHour")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("AutoTracker.Models.CustomerSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignaturePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("CustomerSignatures");
                });

            modelBuilder.Entity("AutoTracker.Models.JobAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("JobAuditLogs");
                });

            modelBuilder.Entity("AutoTracker.Models.JobDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualCostOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("JobDocuments");
                });

            modelBuilder.Entity("AutoTracker.Models.JobPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClientVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("JobPhotos");
                });

            modelBuilder.Entity("AutoTracker.Models.JobTimelineEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClientVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("JobTimelineEntries");
                });

            modelBuilder.Entity("AutoTracker.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualUnitCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CriticalPart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InvoiceUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuotedUnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalActualCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalQuotedPrice")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleDamageItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.HasIndex("VehicleDamageItemId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AutoTracker.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Consumables")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Labour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Paint")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PanelBeating")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Parts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Polishing")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StripAndAssemble")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sublet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId")
                        .IsUnique();

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("AutoTracker.Models.QuoteLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Panels")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("RepairJobId");

                    b.ToTable("QuoteLineItems");
                });

            modelBuilder.Entity("AutoTracker.Models.RepairJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualConsumablesCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualLabourCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualPaintCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualPartsCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualSubletCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualTotalCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTechnician")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedTechnicianUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionCustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionSignaturePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Profit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("TEXT");

                    b.Property<string>("RfidTagCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTechnicianUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RfidTagCode");

                    b.HasIndex("VehicleId");

                    b.ToTable("RepairJobs");
                });

            modelBuilder.Entity("AutoTracker.Models.RfidTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentRepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRepairJobId")
                        .IsUnique()
                        .HasFilter("CurrentRepairJobId IS NOT NULL");

                    b.HasIndex("TagCode")
                        .IsUnique();

                    b.ToTable("RfidTags");
                });

            modelBuilder.Entity("AutoTracker.Models.RfidTagHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RfidTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.HasIndex("RfidTagId");

                    b.ToTable("RfidTagHistories");
                });

            modelBuilder.Entity("AutoTracker.Models.UserSecurityAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserSecurityAuditLogs");
                });

            modelBuilder.Entity("AutoTracker.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoTracker.Models.VehicleDamageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabourHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaintHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepairType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewSide")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepairJobId");

                    b.ToTable("VehicleDamageItems");
                });

            modelBuilder.Entity("AutoTracker.Models.AppUser", b =>
                {
                    b.HasOne("AutoTracker.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AutoTracker.Models.CalendarEvent", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany()
                        .HasForeignKey("RepairJobId");

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.Checklist", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithOne("Checklist")
                        .HasForeignKey("AutoTracker.Models.Checklist", "RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.ChecklistItem", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany()
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.ClientTrackingAccess", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("TrackingAccesses")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.CustomerSignature", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("CustomerSignatures")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.JobAuditLog", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.JobDocument", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("Documents")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.JobPhoto", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("Photos")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.JobTimelineEntry", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.Part", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("Parts")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Models.VehicleDamageItem", "VehicleDamageItem")
                        .WithMany("Parts")
                        .HasForeignKey("VehicleDamageItemId");

                    b.Navigation("RepairJob");

                    b.Navigation("VehicleDamageItem");
                });

            modelBuilder.Entity("AutoTracker.Models.Quote", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithOne("Quote")
                        .HasForeignKey("AutoTracker.Models.Quote", "RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.QuoteLineItem", b =>
                {
                    b.HasOne("AutoTracker.Models.Quote", "Quote")
                        .WithMany("LineItems")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany()
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.RepairJob", b =>
                {
                    b.HasOne("AutoTracker.Models.Client", "Client")
                        .WithMany("RepairJobs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoTracker.Models.Vehicle", "Vehicle")
                        .WithMany("RepairJobs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoTracker.Models.RfidTag", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "CurrentRepairJob")
                        .WithMany()
                        .HasForeignKey("CurrentRepairJobId");

                    b.Navigation("CurrentRepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.RfidTagHistory", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany()
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Models.RfidTag", "RfidTag")
                        .WithMany("History")
                        .HasForeignKey("RfidTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");

                    b.Navigation("RfidTag");
                });

            modelBuilder.Entity("AutoTracker.Models.Vehicle", b =>
                {
                    b.HasOne("AutoTracker.Models.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoTracker.Models.VehicleDamageItem", b =>
                {
                    b.HasOne("AutoTracker.Models.RepairJob", "RepairJob")
                        .WithMany("DamageItems")
                        .HasForeignKey("RepairJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairJob");
                });

            modelBuilder.Entity("AutoTracker.Models.Client", b =>
                {
                    b.Navigation("RepairJobs");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoTracker.Models.Quote", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("AutoTracker.Models.RepairJob", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Checklist");

                    b.Navigation("CustomerSignatures");

                    b.Navigation("DamageItems");

                    b.Navigation("Documents");

                    b.Navigation("Parts");

                    b.Navigation("Photos");

                    b.Navigation("Quote");

                    b.Navigation("TimelineEntries");

                    b.Navigation("TrackingAccesses");
                });

            modelBuilder.Entity("AutoTracker.Models.RfidTag", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("AutoTracker.Models.Vehicle", b =>
                {
                    b.Navigation("RepairJobs");
                });

            modelBuilder.Entity("AutoTracker.Models.VehicleDamageItem", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
